# Generated by Django 5.2.8 on 2025-11-13 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('media_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('game', 'Game'), ('video', 'Video'), ('artwork', 'Artwork'), ('music', 'Music')], max_length=50)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('content_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media Content',
                'verbose_name_plural': 'Media Content',
                'ordering': ['-created_at'],
            },
        ),
    ]
